### ISSUE TITLE
[FEATURE] 메인 탭바 코디네이터 추가

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/alarm-ios#10]
## Description

- 메인 탭바 컨트롤러를 사용하기 위해 메인 탭바 코디네이터를 추가합니다.

## Tasks

- [x] Coordinator 프로토콜 채택
- [x] 메인 탭바 아이템 타입 정의
- [x] 타입에 따라 화면을 구성
