### ISSUE TITLE
이슈 템플릿 구성

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/alarm-ios#3]
## Description

- 프로젝트에서 일관된 필수 항목을 작성할 수 있도록 이슈 템플릿을 사전에 구성합니다.
- 적절한 가이드라인을 통해 이슈 트래킹 시간을 절약할 수 있습니다.

## Tasks

- [x] 버그 리포트 파일
- [x] 기능 리포트 파일
- [x] 리팩토링 리포트 파일
- [x] 일반 리포트 파일
