### ISSUE TITLE
[FEATURE] 애플리케이션 Scene 설정

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/alarm-ios#7]
## Description

- 프로젝트를 처음 생성하면 자동으로 구성되는 스토리보드를 제거합니다.
- Info.plist 등 구성 정보를 변경하고 SceneDelegate의 윈도우를 재정의 합니다.

## Tasks

- [x] 메인 스토리보드 제거
- [x] 번들 네임 제거
- [x] Info.plist 정보 제거
- [x] SceneDelegate 수정

**Comment by yujinkim1** [comment]
코디네이터 패턴 사용할지 의논 필요
